//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se_liga_mogi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servidores
    {
        public int id_servidor { get; set; }
        public string rgf { get; set; }
        public string nome_servidor { get; set; }
        public string cargo_servidor { get; set; }
        public decimal salario_servidor { get; set; }
    }
}
