//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se_liga_mogi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presenca_parlamentares
    {
        public int id_parlamentar { get; set; }
        public System.DateTime data_presença { get; set; }
        public bool falta_ou_nao { get; set; }
        public string motivo_da_falta { get; set; }
    
        public virtual parlamentares parlamentares { get; set; }
    }
}
