//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se_liga_mogi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servidores
    {
        public int id_servidor { get; set; }
        public string rgf { get; set; }
        public string nome_servidor { get; set; }
        public string cargo_servidor { get; set; }
        public decimal salario_servidor { get; set; }
        public Nullable<decimal> salario_liquido_servidor { get; set; }
        public Nullable<decimal> descontos_servidor { get; set; }
    
        public virtual descontos_servidores descontos_servidores { get; set; }
        public virtual diarias_e_passagens diarias_e_passagens { get; set; }
        public virtual remuneracao_servidores remuneracao_servidores { get; set; }
    }
}
