//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se_liga_mogi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projetos_de_lei
    {
        public string numero_projeto { get; set; }
        public string autor_projeto { get; set; }
        public string assunto { get; set; }
        public string anotacao { get; set; }
        public string ano_projeto { get; set; }
    }
}
