//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se_liga_mogi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servidores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servidores()
        {
            this.descontos_servidores = new HashSet<descontos_servidores>();
            this.diarias_e_passagens = new HashSet<diarias_e_passagens>();
            this.remuneracao_servidores = new HashSet<remuneracao_servidores>();
        }
    
        public int rgf { get; set; }
        public string nome_servidor { get; set; }
        public string cargo_servidor { get; set; }
        public decimal salario_servidor { get; set; }
        public decimal salario_liquido_servidor { get; set; }
        public decimal descontos_servidor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<descontos_servidores> descontos_servidores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diarias_e_passagens> diarias_e_passagens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<remuneracao_servidores> remuneracao_servidores { get; set; }
    }
}
